package com.projet.model;
// Generated 14 févr. 2023, 03:22:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "bd_projet_agl")
public class Administrateur implements java.io.Serializable {

	private Integer idEmploye;
	private String nom;
	private String prenom;
	private String sexe;
	private String telephone;
	private String email;
	private String domicile;
	private String nomUtilisateur;
	private String mdp;

	public Administrateur() {
	}

	public Administrateur(String nom, String prenom, String sexe, String telephone, String email, String domicile,
			String nomUtilisateur, String mdp) {
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.telephone = telephone;
		this.email = email;
		this.domicile = domicile;
		this.nomUtilisateur = nomUtilisateur;
		this.mdp = mdp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_EMPLOYE", unique = true, nullable = false)
	public Integer getIdEmploye() {
		return this.idEmploye;
	}

	public void setIdEmploye(Integer idEmploye) {
		this.idEmploye = idEmploye;
	}

	@Column(name = "NOM", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "SEXE", length = 30)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "TELEPHONE", length = 30)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DOMICILE", length = 30)
	public String getDomicile() {
		return this.domicile;
	}

	public void setDomicile(String domicile) {
		this.domicile = domicile;
	}

	@Column(name = "NOM_UTILISATEUR", length = 30)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "MDP", length = 30)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

}
