package com.projet.model;
// Generated 14 févr. 2023, 03:22:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NumeroDepart generated by hbm2java
 */
@Entity
@Table(name = "numero_depart", catalog = "bd_projet_agl")
public class NumeroDepart implements java.io.Serializable {

	private Integer idNumDepart;
	private String numero;

	public NumeroDepart() {
	}

	public NumeroDepart(String numero) {
		this.numero = numero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_numDepart", unique = true, nullable = false)
	public Integer getIdNumDepart() {
		return this.idNumDepart;
	}

	public void setIdNumDepart(Integer idNumDepart) {
		this.idNumDepart = idNumDepart;
	}

	@Column(name = "numero", nullable = false, length = 30)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
