package com.projet.model;
// Generated 14 févr. 2023, 03:22:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "bd_projet_agl")
public class Reservation implements java.io.Serializable {

	private Integer numReservation;
	private int idEmploye;
	private int numtransaction;
	private int idClient;
	private String dateDepart;
	private String numDepart;
	private String villeDepart;
	private String villeArrivee;
	private int prix;
	
	
	
	private Client client;
	
	

	public Reservation() {
	}

	public Reservation(int idEmploye, int numtransaction, int idClient, int prix) {
		this.idEmploye = idEmploye;
		this.numtransaction = numtransaction;
		this.idClient = idClient;
		this.prix = prix;
	}
	//Mon constructeur personnel
	public Reservation(int numtransaction, String dateDepart, String numDepart, String villeDepart,
			String villeArrivee/*, Client client*/) {
		super();
		this.numtransaction = numtransaction;
		this.dateDepart = dateDepart;
		this.numDepart = numDepart;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
		this.client = client;
		
		/*.nom = nom;
		this.code =code;*/
	}

	public Reservation(int idEmploye, int numtransaction, int idClient, String dateDepart, String numDepart,
			String villeDepart, String villeArrivee, int prix) {
		this.idEmploye = idEmploye;
		this.numtransaction = numtransaction;
		this.idClient = idClient;
		this.dateDepart = dateDepart;
		this.numDepart = numDepart;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
		this.prix = prix;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NUM_RESERVATION", unique = true, nullable = false)
	public Integer getNumReservation() {
		return this.numReservation;
	}

	public void setNumReservation(Integer numReservation) {
		this.numReservation = numReservation;
	}

	@Column(name = "ID_EMPLOYE", nullable = false)
	public int getIdEmploye() {
		return this.idEmploye;
	}

	public void setIdEmploye(int idEmploye) {
		this.idEmploye = idEmploye;
	}

	@Column(name = "NUMTRANSACTION", nullable = false)
	public int getNumtransaction() {
		return this.numtransaction;
	}

	public void setNumtransaction(int numtransaction) {
		this.numtransaction = numtransaction;
	}

	@Column(name = "ID_CLIENT", nullable = false)
	public Client getClient() {
		return this.client;
	}
	
	public void setClient(Client client) {
		this.client  = client;
	}
	
	
	public int getIdClient() {
		return this.idClient;
	}
	
	

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "DATE_DEPART", length = 30)
	public String getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(String dateDepart) {
		this.dateDepart = dateDepart;
	}

	@Column(name = "NUM_DEPART", length = 30)
	public String getNumDepart() {
		return this.numDepart;
	}

	public void setNumDepart(String numDepart) {
		this.numDepart = numDepart;
	}

	@Column(name = "VILLE_DEPART", length = 30)
	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	@Column(name = "VILLE_ARRIVEE", length = 30)
	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	@Column(name = "Prix", nullable = false)
	public int getPrix() {
		return this.prix;
	}

	public void setPrix(int prix) {
		this.prix = prix;
	}

}
