package com.projet.model;
// Generated 6 févr. 2023, 09:29:42 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "bd_projet_agl")
public class Reservation implements java.io.Serializable {

	private Integer numReservation;
	private int idEmploye;
	private int numtransaction;
	private int idClient;
	private Date dateDepart;
	private Integer numDepart;
	private String villeDepart;
	private String villeArrivee;
	private int prix;

	public Reservation() {
	}

	public Reservation(int idEmploye, int numtransaction, int idClient, int prix) {
		this.idEmploye = idEmploye;
		this.numtransaction = numtransaction;
		this.idClient = idClient;
		this.prix = prix;
	}

	public Reservation(int idEmploye, int numtransaction, int idClient, Date dateDepart, Integer numDepart,
			String villeDepart, String villeArrivee, int prix) {
		this.idEmploye = idEmploye;
		this.numtransaction = numtransaction;
		this.idClient = idClient;
		this.dateDepart = dateDepart;
		this.numDepart = numDepart;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
		this.prix = prix;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NUM_RESERVATION", unique = true, nullable = false)
	public Integer getNumReservation() {
		return this.numReservation;
	}

	public void setNumReservation(Integer numReservation) {
		this.numReservation = numReservation;
	}

	@Column(name = "ID_EMPLOYE", nullable = false)
	public int getIdEmploye() {
		return this.idEmploye;
	}

	public void setIdEmploye(int idEmploye) {
		this.idEmploye = idEmploye;
	}

	@Column(name = "NUMTRANSACTION", nullable = false)
	public int getNumtransaction() {
		return this.numtransaction;
	}

	public void setNumtransaction(int numtransaction) {
		this.numtransaction = numtransaction;
	}

	@Column(name = "ID_CLIENT", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEPART", length = 10)
	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	@Column(name = "NUM_DEPART")
	public Integer getNumDepart() {
		return this.numDepart;
	}

	public void setNumDepart(Integer numDepart) {
		this.numDepart = numDepart;
	}

	@Column(name = "VILLE_DEPART", length = 30)
	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	@Column(name = "VILLE_ARRIVEE", length = 30)
	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	@Column(name = "Prix", nullable = false)
	public int getPrix() {
		return this.prix;
	}

	public void setPrix(int prix) {
		this.prix = prix;
	}

}
