package com.projet.model;
// Generated 6 févr. 2023, 09:29:42 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "bd_projet_agl")
public class Transaction implements java.io.Serializable {

	private Integer numtransaction;
	private Date dateTransaction;
	private Float montant;

	public Transaction() {
	}

	public Transaction(Date dateTransaction, Float montant) {
		this.dateTransaction = dateTransaction;
		this.montant = montant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NUMTRANSACTION", unique = true, nullable = false)
	public Integer getNumtransaction() {
		return this.numtransaction;
	}

	public void setNumtransaction(Integer numtransaction) {
		this.numtransaction = numtransaction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_TRANSACTION", length = 10)
	public Date getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(Date dateTransaction) {
		this.dateTransaction = dateTransaction;
	}

	@Column(name = "MONTANT", precision = 8)
	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

}
