package com.projet.model;
// Generated 14 févr. 2023, 03:22:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Villes generated by hbm2java
 */
@Entity
@Table(name = "villes", catalog = "bd_projet_agl")
public class Villes implements java.io.Serializable {

	private Integer idVille;
	private String ville;

	public Villes() {
	}

	public Villes(String ville) {
		this.ville = ville;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ville", unique = true, nullable = false)
	public Integer getIdVille() {
		return this.idVille;
	}

	public void setIdVille(Integer idVille) {
		this.idVille = idVille;
	}

	@Column(name = "ville", nullable = false, length = 30)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

}
